name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      echo ${{ secrets.VPS_SSH }} > secret
      chmod 600 secret_key
      ssh -oStrictHostKeyChecking=no root@practice.kakomimasu.website -i secret_key "cd ~/Kakomimasu && git pull && touch hoge"
      
