name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run fmt
        run: |
          deno fmt -c deno.json --check
      - name: Run lint
        run: |
          deno lint -c deno.json
      - name: Run test
        run: |
          deno test -A
