on: [push]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with: 
          deno-version: v1.x
      - name: Run fmt
        run: |
          deno fmt --check
      - name: Run lint
        run: |
          deno lint
      - name: Run cache & check(apiserver)
        run: |
          deno cache ./apiserver/apiserver.ts
      - name: Run cache & check(viewer)
        run: |
          deno cache --import-map ./pages/import-map.json --config ./pages/tsconfig.json ./pages/route.tsx
      - name: Run test(Unix)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          deno run -A ./apiserver/apiserver.ts > /dev/null &
          deno test -A
      - name: Run test(Windows)
        if: runner.os == 'Windows'
        run: |
          deno run -A ./apiserver/apiserver.ts > $null &
          deno test -A
